//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BO_CHILDS
    {
        public long BO_PARENT_ID { get; set; }
        public long BO_CHILD_ID { get; set; }
        public string RELATION { get; set; }
    }
}
