//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BO_ROLE
    {
        public long BO_ROLE_ID { get; set; }
        public long META_BO_ID { get; set; }
        public string ROLE_ID { get; set; }
        public Nullable<bool> CAN_READ { get; set; }
        public Nullable<bool> CAN_WRITE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<long> PAGE_ID { get; set; }
    }
}
