//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BON_DA
    {
        public long BO_ID { get; set; }
        public string REF { get; set; }
        public Nullable<System.DateTime> VALIDATED_DATE { get; set; }
        public string VALIDATED_BY { get; set; }
        public string DEMANDEUR { get; set; }
        public Nullable<System.DateTime> DATE_SOUHAITE { get; set; }
        public Nullable<int> DURATION { get; set; }
        public string OBSERVATION { get; set; }
        public Nullable<long> FOURNISSEUR_ID { get; set; }
        public string ORDER_REF { get; set; }
        public string PAYEMENT_MODE { get; set; }
        public string PAYEMENT_CONDITION { get; set; }
        public string REF_BON_LIVRAISON { get; set; }
    
        public virtual BO BO { get; set; }
    }
}
