//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FAISEntities : DbContext
    {
        public FAISEntities()
            : base("name=FAISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BO> BO { get; set; }
        public virtual DbSet<BO_CHILDS> BO_CHILDS { get; set; }
        public virtual DbSet<META_BO> META_BO { get; set; }
        public virtual DbSet<META_FIELD> META_FIELD { get; set; }
        public virtual DbSet<VERSIONS> VERSIONS { get; set; }
    }
}
