//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIF
    {
        public int ID_NOTIF { get; set; }
        public string VALIDATOR { get; set; }
        public Nullable<int> ETAT { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
