//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIF
    {
        public int ID_NOTIF { get; set; }
        public string VALIDATOR { get; set; }
        public Nullable<int> ETAT { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
