//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        public int TASK_ID { get; set; }
        public Nullable<int> BO_ID { get; set; }
        public string JSON_DATA { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> ETAT { get; set; }
        public Nullable<int> TASK_LEVEL { get; set; }
        public string TASK_TYPE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
    }
}
