//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        public int TASK_ID { get; set; }
        public Nullable<int> BO_ID { get; set; }
        public string JSON_DATA { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> ETAT { get; set; }
        public Nullable<int> TASK_LEVEL { get; set; }
        public string TASK_TYPE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
    }
}
