//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW
    {
        public long BO_ID { get; set; }
        public string LIBELLE { get; set; }
        public Nullable<int> ACTIVE { get; set; }
        public string ITEMS { get; set; }
    }
}
