//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW
    {
        public long BO_ID { get; set; }
        public string LIBELLE { get; set; }
        public Nullable<int> ACTIVE { get; set; }
        public string ITEMS { get; set; }
    }
}
