/****** Object:  Table [dbo].[BO_ROLE]    Script Date: 14-Mar-19 11:23:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE  TABLE [dbo].[BO_ROLE](
	[BO_ROLE_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[META_BO_ID] [bigint] NOT NULL,
	[ROLE_ID] [nvarchar](128) NOT NULL,
	[CAN_READ] [bit] NULL,
	[CAN_WRITE] [bit] NULL,
	[CREATED_BY] [varchar](100) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [varchar](100) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[STATUS] [varchar](10) NULL,
 CONSTRAINT [PK_BO_ROLE] PRIMARY KEY CLUSTERED 
(
	[BO_ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BO_ROLE] ADD  CONSTRAINT [DF_BO_ROLE__READ]  DEFAULT ((0)) FOR [CAN_READ]
GO

ALTER TABLE [dbo].[BO_ROLE] ADD  CONSTRAINT [DF_BO_ROLE__WRITE]  DEFAULT ((0)) FOR [CAN_WRITE]
GO

ALTER TABLE [dbo].[BO_ROLE] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[BO_ROLE] ADD  DEFAULT (getdate()) FOR [UPDATED_DATE]
GO


