CREATE TABLE {TABLE_NAME} (
[BO_ID] bigint NOT NULL,
{FIELDS}
[CREATED_BY] varchar(100) NULL ,
[CREATED_DATE] datetime NULL DEFAULT getdate() ,
[UPDATED_BY] varchar(100) NULL ,
[UPDATED_DATE] datetime NULL DEFAULT getdate() ,
[STATUS] varchar(10) NULL ,
PRIMARY KEY ([BO_ID])
);

CREATE INDEX [IDX_CREATED_DATE] ON {TABLE_NAME}
([CREATED_DATE] ASC);

CREATE INDEX [IDX_CREATED_BY] ON {TABLE_NAME}
([CREATED_BY] ASC);

CREATE INDEX [IDX_UPDATED_DATE] ON {TABLE_NAME}
([UPDATED_DATE] ASC);

CREATE INDEX [IDX_UPDATED_BY] ON {TABLE_NAME}
([UPDATED_BY] ASC);