CREATE TABLE {0} (
[BO_ID] bigint NOT NULL,
{1}
[CREATED_BY] varchar(100) NULL ,
[CREATED_DATE] datetime NULL DEFAULT getdate() ,
[UPDATED_BY] varchar(100) NULL ,
[UPDATED_DATE] datetime NULL DEFAULT getdate() ,
[STATUS] varchar(10) NULL ,
PRIMARY KEY ([BO_ID])
);

CREATE INDEX [IDX_CREATED_DATE] ON {0}
([CREATED_DATE] ASC);

CREATE INDEX [IDX_CREATED_BY] ON {0}
([CREATED_BY] ASC);

CREATE INDEX [IDX_UPDATED_DATE] ON {0}
([UPDATED_DATE] ASC);

CREATE INDEX [IDX_UPDATED_BY] ON {0}
([UPDATED_BY] ASC);
