CREATE TABLE {TABLE_NAME} (
[{TABLE_NAME}_ID] bigint NOT NULL IDENTITY(1,1) ,
[CREATED_BY] varchar(100) NULL ,
[CREATED_DATE] datetime NULL DEFAULT getdate() ,
[UPDATED_BY] varchar(100) NULL ,
[UPDATED_DATE] datetime NULL DEFAULT getdate() ,
[STATUS] char(10) NULL ,
PRIMARY KEY ([{TABLE_NAME}_ID])
)

GO

CREATE INDEX [IDX_CREATED_DATE] ON {TABLE_NAME}
([CREATED_DATE] ASC) 
GO

CREATE INDEX [IDX_CREATED_BY] ON {TABLE_NAME}
([CREATED_BY] ASC) 
GO

CREATE INDEX [IDX_UPDATED_DATE] ON {TABLE_NAME}
([UPDATED_DATE] ASC) 
GO

CREATE INDEX [IDX_UPDATED_BY] ON {TABLE_NAME}
([UPDATED_BY] ASC) 
GO

