CREATE TABLE BO (
[BO_ID] bigint NOT NULL IDENTITY(1,1) ,
[CREATED_BY] varchar(100) NULL ,
[CREATED_DATE] datetime NULL DEFAULT getdate() ,
[UPDATED_BY] varchar(100) NULL ,
[UPDATED_DATE] datetime NULL DEFAULT getdate() ,
[STATUS] char(10) NULL ,
BO_TYPE varchar(100) NULL,
PRIMARY KEY ([BO_ID])
)

GO

CREATE INDEX [IDX_CREATED_DATE] ON BO
([CREATED_DATE] ASC) 
GO

CREATE INDEX [IDX_CREATED_BY] ON BO
([CREATED_BY] ASC) 
GO

CREATE INDEX [IDX_UPDATED_DATE] ON BO
([UPDATED_DATE] ASC) 
GO

CREATE INDEX [IDX_UPDATED_BY] ON BO
([UPDATED_BY] ASC) 
GO

CREATE TABLE BO_CHILDS (
[BO_PARENT_ID] bigint NOT NULL ,
[BO_CHILD_ID] bigint NOT NULL ,
PRIMARY KEY ([BO_PARENT_ID], [BO_CHILD_ID])
)

GO



CREATE TABLE META_BO (
[META_BO_ID] bigint NOT NULL IDENTITY(1,1) ,
[BO_NAME] varchar(100) ,
[VERSION] int ,
[CREATED_BY] varchar(100) ,
[CREATED_DATE] datetime DEFAULT getdate() ,
[UPDATED_BY] varchar(100) NULL ,
[UPDATED_DATE] datetime NULL DEFAULT getdate() ,
[STATUS] char(10) NULL ,
PRIMARY KEY ([META_BO_ID])
)

GO

CREATE INDEX [IDX_CREATED_DATE] ON META_BO
([CREATED_DATE] ASC) 
GO

CREATE INDEX [IDX_CREATED_BY] ON META_BO
([CREATED_BY] ASC) 
GO

CREATE INDEX [IDX_UPDATED_DATE] ON META_BO
([UPDATED_DATE] ASC) 
GO

CREATE INDEX [IDX_UPDATED_BY] ON META_BO
([UPDATED_BY] ASC) 
GO


CREATE TABLE META_FIELD (
[META_FIELD_ID] bigint NOT NULL IDENTITY(1,1) ,
[META_BO_ID] bigint NOT NULL,

[DB_NAME] varchar(100) NOT NULL ,
[DB_TYPE] varchar(20) NOT NULL ,
[DB_NULL] int NOT NULL Default(1),

[GRID_NAME] varchar(100) NOT NULL ,
[GRID_FORMAT] varchar(100) NULL,
[GRID_SHOW] int NULL Default(1),

[FORM_NAME] varchar(100) NULL,
[FORM_FORMAT] varchar(100) NULL,
[FORM_TYPE] varchar(100) NOT NULL,
[FORM_SOURCE] varchar(1000) NULL,
[FORM_SHOW] int NULL Default(1),

[CREATED_BY] varchar(100) NOT NULL,
[CREATED_DATE] datetime DEFAULT getdate() ,
[UPDATED_BY] varchar(100) NULL ,
[UPDATED_DATE] datetime NULL DEFAULT getdate() ,
[STATUS] char(10) NULL ,
PRIMARY KEY ([META_FIELD_ID]),
FOREIGN KEY ([META_BO_ID]) REFERENCES [META_BO]([META_BO_ID])
)

GO

CREATE INDEX [IDX_CREATED_DATE] ON META_FIELD
([CREATED_DATE] ASC) 
GO

CREATE INDEX [IDX_CREATED_BY] ON META_FIELD
([CREATED_BY] ASC) 
GO

CREATE INDEX [IDX_UPDATED_DATE] ON META_FIELD
([UPDATED_DATE] ASC) 
GO

CREATE INDEX [IDX_UPDATED_BY] ON META_FIELD
([UPDATED_BY] ASC) 
GO